### ISSUE TITLE
Add Rectangular grid support

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/gridded#1]
Rectangular but not necessarily regular.

Southern California ROMS from GOODS should be an example.

**Comment by ChrisBarker-NOAA** [comment]
Another example:

ECWMF, as found here:

https://github.com/NOAA-ORR-ERD/PyGnome/issues/31

**Comment by ChrisBarker-NOAA** [comment]
@jay-hennen: Is this done?

**Comment by jay-hennen** [comment]
Yup
