### ISSUE TITLE
specifying custom grid_topolgy varibles?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/gridded#18]
The constructor for Dataset takes a grid_topology parameter:

```
class Dataset():
    def __init__(self, ncfile=None, grid=None, variables=None, grid_topology=None,):
```

but it doesn't appear to be used :-(

**Comment by ChrisBarker-NOAA** [comment]
OK, I see that load_from_varnames() is Not Implemented, so that explains it.

But maybe there should be something in the __init__.

-CHB

**Comment by jay-hennen** [comment]
The fact the grid_topology parameter is not used is an oversight and a bug. It should be passed into the Grid constructor on line 49:
`self.grid = Grid.from_netCDF(filename=self.filename, dataset=self.nc_dataset, grid_topology=grid_topology)`

**Comment by ChrisBarker-NOAA** [comment]
yup -- I've done that now.

**Comment by ChrisBarker-NOAA** [comment]
looking more, I found that ``Grid.from_netCDF`` supports passing grid_topology through.

so I've added that code to ``Dataset.__init__``

Whether it works or has been tested is another story...

-CHB
