### ISSUE TITLE
Documentation: improvements to Design Principles page 

### ISSUE THREAD

**Issue by OlyDLG** [NOAA-ORR-ERD/gridded#48]
https://noaa-orr-erd.github.io/gridded/api_reference.html#design-principles

E.g. "...and ideally to no have to even know what...", "These are for the most part “duck typed”," (Antecedent of "These" is unclear)

Since I'm reading the docs to try to get up to speed, I figure I might as well log "issues" when I encounter them.

**Comment by ChrisBarker-NOAA** [comment]
Thanks -- PR's accepted if you have better wording to suggest.

these pages are generated from the RST here:

https://github.com/NOAA-ORR-ERD/gridded/tree/master/docs/source

**Comment by ChrisBarker-NOAA** [comment]
I clarified a bit in this commit:

4b5dfb2eb2b

close this if that makes sense.

**Comment by OlyDLG** [comment]
Yup. (I actually didn't expect such an efficient response: I was kind of doing it more to leave myself notes of where to improve the doc as part of my volunteer contribution once I've forked--please feel free to regard future Doc issues that way, if you wish.)

**Comment by ChrisBarker-NOAA** [comment]
Well, once I was thinking about it, I figured I'd go in and whip something out. But I won't usually be that fast :-)

Thanks.
