### ISSUE TITLE
example load_arbitrary_ugrid.py doesn't work

### ISSUE THREAD

**Issue by SBFRF** [NOAA-ORR-ERD/gridded#50]
Hey Guys, 
from previous issue #49 `load_arbitrary_ugrid.py` doesn't work.

**Comment by ChrisBarker-NOAA** [comment]
I've take a look, and it turns out there's some real work to be done here, so this isn't going to work anytime soon.

See: #52

**Comment by ChrisBarker-NOAA** [comment]
NOTE: I just commented out the "save the grid back out" line -- that is not working.

But it does now (current master) work for loading -- it should give you a valid gridded.Dataset to do other things with.

-CHB

**Comment by SBFRF** [comment]
Hey @ChrisBarker-NOAA well that's a bummer, because this example followed my use case most closely (e.g. make UGRID compliant netCDF file from non-compliant netCDF file).  Is there any timeline on this or should I begin working a different solution to my problem (maybe pyugrid can help)?

**Comment by ChrisBarker-NOAA** [comment]
Sorry to hear that -- I'd always intended gridded and pyugrid before it, to be used this way. But no one working on the code had an operational need, so it was never quite completed.

pyugrid won't help -- all its code is in gridded -- and it never quite grew the ability to save out variables either.

I'm afraid I don't have much time to work on this now -- but if you are going to work on a solution anyway, maybe you'd be interested in doing it within the gridded framework? If you want to do that, I'd be glad to point you to where in the code to look to get started.
