### ISSUE TITLE
CI tests

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [NOAA-ORR-ERD/gridded#7]
Set up CI tests!

It'd be really nice to have tests run on gitHub pushes -- particularly to capture py2/py3 issues, etc.

**Comment by rsignell-usgs** [comment]
Just pushed some changes to notebook.   About to board flight home.  Hope to log in tomorrow and see how things are going....

**Comment by ChrisBarker-NOAA** [comment]
I added a travis.yaml, and tried to get it hooked up but travis does not seem to be running.

We need to debug this someday...

**Comment by ChrisBarker-NOAA** [comment]
travis is running, though not working yet.

conda configuration not quite right

**Comment by ChrisBarker-NOAA** [comment]
Got it working -- whoo hoo!

The tests are failing -- but that's a good thing, yes? At least good that we know they failed.

**Comment by rsignell-usgs** [comment]
Nice work guys!

**Comment by ChrisBarker-NOAA** [comment]
Thanks -- I feel like I didn't get much done. But did get some good
infrastructure in place.

Now we need to keep the momentum going....

-CHB

On Jul 16, 2017, at 7:03 PM, Rich Signell <notifications@github.com> wrote:

Nice work guys!

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/NOAA-ORR-ERD/gridded/issues/7#issuecomment-315647716>,
or mute the thread
